-- MySQL Script generated by MySQL Workbench
-- Wed Jul 30 12:01:24 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`store` (
  `id_store` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `loc_ref` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_store`),
  UNIQUE INDEX (`loc_ref` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`guest_check`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`guest_check` (
  `id_guest_check` INT NULL DEFAULT NULL,
  `store_id` INT NOT NULL,
  `chk_num` INT NULL DEFAULT NULL,
  `opn_bus_dt` DATE NULL DEFAULT NULL,
  `opn_utc` DATETIME NULL DEFAULT NULL,
  `clsd_bus_dt` DATE NULL DEFAULT NULL,
  `clsd_utc` DATETIME NULL DEFAULT NULL,
  `gst_cnt` INT NULL DEFAULT NULL,
  `sub_ttl` DECIMAL(10,2) NULL DEFAULT NULL,
  `chk_ttl` DECIMAL(10,2) NULL DEFAULT NULL,
  `dsc_ttl` DECIMAL(10,2) NULL DEFAULT NULL,
  `pay_ttl` DECIMAL(10,2) NULL DEFAULT NULL,
  `bal_due_ttl` DECIMAL(10,2) NULL DEFAULT NULL,
  `tbl_num` INT NULL DEFAULT NULL,
  `tbl_name` VARCHAR(50) NULL DEFAULT NULL,
  `emp_num` INT NULL DEFAULT NULL,
  `clsd_flag` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_guest_check`),
  INDEX (`store_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`store_id`)
    REFERENCES `mydb`.`store` (`id_store`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detail_line`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detail_line` (
  `id_detail_line` INT NULL DEFAULT NULL,
  `guest_check_id` INT NOT NULL,
  `line_num` INT NULL DEFAULT NULL,
  `dtl_id` INT NULL DEFAULT NULL,
  `detail_utc` DATETIME NULL DEFAULT NULL,
  `bus_dt` DATE NULL DEFAULT NULL,
  `dsp_ttl` DECIMAL(10,2) NULL DEFAULT NULL,
  `dsp_qty` DECIMAL(10,2) NULL DEFAULT NULL,
  `agg_ttl` DECIMAL(10,2) NULL DEFAULT NULL,
  `agg_qty` DECIMAL(10,2) NULL DEFAULT NULL,
  `seat_num` INT NULL DEFAULT NULL,
  `svc_rnd_num` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_detail_line`),
  INDEX (`guest_check_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`guest_check_id`)
    REFERENCES `mydb`.`guest_check` (`id_guest_check`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`menu_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`menu_item` (
  `id_menu_item` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `detail_line_id` INT NOT NULL,
  `mi_num` INT NULL DEFAULT NULL,
  `mod_flag` TINYINT(1) NULL DEFAULT NULL,
  `incl_tax` DECIMAL(10,2) NULL DEFAULT NULL,
  `prc_lvl` INT NULL DEFAULT NULL,
  `active_taxes` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_menu_item`),
  INDEX (`detail_line_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`detail_line_id`)
    REFERENCES `mydb`.`detail_line` (`id_detail_line`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tax` (
  `id_tax` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `guest_check_id` INT NOT NULL,
  `tax_num` INT NULL DEFAULT NULL,
  `txbl_sls_ttl` DECIMAL(10,2) NULL DEFAULT NULL,
  `tax_coll_ttl` DECIMAL(10,2) NULL DEFAULT NULL,
  `tax_rate` DECIMAL(5,4) NULL DEFAULT NULL,
  `type` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_tax`),
  INDEX (`guest_check_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`guest_check_id`)
    REFERENCES `mydb`.`guest_check` (`id_guest_check`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
